### ISSUE TITLE
Compiling with -custom fails on ocaml_mtime_elapsed_ns

### ISSUE THREAD

**Issue by orbitz** [dbuenzli/mtime#16]
Using the `min.ml` example in the documentation.

    ocamlfind ocamlc -package mtime.os -linkpkg -custom -o min.byte min.ml
    /tmp/camlprimfa1abf-4fadb0.o:(.data+0x9d8): undefined reference to `ocaml_mtime_elapsed_ns'
    clang-3.9: error: linker command failed with exit code 1 (use -v to see invocation)
    File "min.ml", line 1:
    Error: Error while building custom runtime system

**Comment by dbuenzli** [comment]
Details please. Works here on osx 10.2.2 with ocaml 4.03.

**Comment by dbuenzli** [comment]
A sorry I used the invocation mentioned in `min.ml`. It seems it fails in `-custom` mode.

**Comment by dbuenzli** [comment]
It seems we only have the stub flags mentioned for dynamic linking: 

```
> ocamlobjinfo $(opam config var mtime:lib)/os/mtime.cma | grep "Extra"
Extra C object files:
Extra C options:
Extra dynamically-loaded libraries: -lmtime_stubs
```

**Comment by dbuenzli** [comment]
Maybe I should simply switch to @pqwy's `ocb-stubblr`.

**Comment by dbuenzli** [comment]
I'll try to have a look at this this afternoon, meanwhile you can simply compile with: 

```
ocamlfind ocamlc -package mtime.os -cclib -lmtime_stubs -linkpkg -custom -o min.byte min.ml
```

**Comment by dbuenzli** [comment]
@orbitz could you please confirm the fix works for you by trying with:

```
opam pin add mtime https://github.com/dbuenzli/mtime.git 
```

**Comment by orbitz** [comment]
I can confirm it works for me, thank you for the fast turn around.
