### ISSUE TITLE
support older versions of OCaml?

### ISSUE THREAD

**Issue by c-cube** [dbuenzli/mtime#23]
I could not find the reason why 4.03 is now needed.

**Comment by dbuenzli** [comment]
I'm not sure either if you can confirm me it works on a lower one I can certainly PR the opam repo.

**Comment by c-cube** [comment]
So it's because of `Int64.equal`, it seems. However this is just implemented in terms of `Pervasives.compare` afaict.

**Comment by dbuenzli** [comment]
Arf. Thanks for the info.

**Comment by dbuenzli** [comment]
Btw. @c-cube I think that at least documentation wise there a lot of interest in moving towards 4.03, it's the first release that allows `odoc` (and hence `odig`) to provide correct outputs (the `4.02.*` line was systematically broken w.r.t. to `cmt[i]` files).

**Comment by c-cube** [comment]
I see, that's a good reason I guess. The only issue is that when someone tries to install some of my programs (typically researchers not very familiar with ocaml or opam) they might have older versions of ocaml. But I'll just explain how to opam switch…

**Comment by dbuenzli** [comment]
> The only issue is that when someone tries to install some of my programs (typically researchers not very familiar with ocaml or opam) they might have older versions of ocaml.

I see. I understand it can be an annoyance. 

> But I'll just explain how to opam switch…

If these users are not interested in ocaml per se it may be worth investigating [`opam-bundle`](https://discuss.ocaml.org/t/ann-opam-bundle-0-1-generate-self-contained-distributable-source-package-bundles/291) to distribute them software.

**Comment by c-cube** [comment]
Good to know, thank you.
