### ISSUE TITLE
Add documentation on accessing Mtime_clock

### ISSUE THREAD

**Issue by basus** [dbuenzli/mtime#24]
It took me some trial and error and digging around to figure out how to build using the `Mtime_clock` module. In particular, if using the `jbuilder` build system, one has to list `mtime.clock.os` as a dependency, rather than the obvious `mtime.clock`. I think the same is true for `oasis`.

It would be helpful to new users if this detail were listed somewhere, perhaps straight in the `README.md` where `Mtime_clock` is first mentioned, and also in the API docs for that module.

**Comment by dbuenzli** [comment]
I'll add something at some point. But note that the sample code that comes with the library has precise build instructions.

**Comment by dbuenzli** [comment]
Could certainly be made better but mentioned the implementation in the preamble of `Mtime_clock` a bit in 414a6b8930916e96
