### ISSUE TITLE
Conversion functions for timestamps

### ISSUE THREAD

**Issue by Armael** [dbuenzli/mtime#27]
I'm trying to convert back and forth between `Mtime.t` and the `timespec` structure as described in the C bindings here: https://github.com/dsheets/ocaml-unix-time/blob/master/lib/time.mli . 

Currently, to convert from `Mtime.t` to `Timespec.t`, I only found the following way:
```ocaml
let timespec_of_mtime mtime =
  let timestamp_ns = Mtime.to_uint64_ns mtime in
  let span = Mtime.Span.of_uint64_ns timestamp_ns in
  let sec = Mtime.Span.to_s span |> Int64.of_float in
  let sec_span = Mtime.Span.of_uint64_ns sec in
  let nsec = Mtime.Span.abs_diff span sec_span in
  Timespec.{ sec; nsec = Mtime.Span.to_uint64_ns nsec |> Int64.to_int }
```

...which seems convoluted, and I'm a bit scared of a loss of precision by going through floats.

Could there be some additional conversion functions from timestamps directly, and maybe also functions to get the fractional part of a timestamp / span? (for example the [rust time stdlib](https://doc.rust-lang.org/std/time/struct.Duration.html#method.subsec_nanos) seems to contain some of these).

**Comment by dbuenzli** [comment]
These floating point constants should not have been introduced, it seems they distracted you from the obvious. What about: 
```ocaml
let timespec_of_mtime mtime = 
  let ns_in_sec = 1_000_000_000L in 
  let ns = Mtime.to_uint64_ns mtime in 
  let sec = Int64.div ns ns_in_sec in 
  let nsec = Int64.rem ns ns_in_sec in 
  Timespec.{ sec; nsec }
```

**Comment by dbuenzli** [comment]
Regarding the request I'm a bit unsure whether it's worth introducing what you suggest.

**Comment by Armael** [comment]
Yes, that sounds more reasonable indeed. I guess by seeing these constants I somehow assumed that I was not supposed to assume that 1s is 10^9 ns (...) and only use the library builtins. Hmm....

I think it would be relatively useful to have these additionnal accessors, but I would understand if you feel it's not worth the hassle.

**Comment by dbuenzli** [comment]
> I somehow assumed that I was not supposed to assume that 1s is 10^9 ns

!? Armael, SCIENCE.

> I think it would be relatively useful to have these additionnal accessors, but I would understand if you feel it's not worth the hassle.

It's really the remainder of a division... and how often you need that function remains unclear to me but I'll keep it open for now.

**Comment by dbuenzli** [comment]
#28 should be done at some point but not now. Closing this.
