### ISSUE TITLE
mtime.1.2.0 fails to build with 5.1.0+trunk

### ISSUE THREAD

**Issue by shakthimaan** [dbuenzli/mtime#45]
When trying to compile `mtime.1.2.0` with the latest `5.1.0+trunk`, we observe the following error:
```
File "myocamlbuild.ml", line 1:
Error: /home/guest/sandmark/_opam/5.1.0+trunk/lib/ocamlbuild/ocamlbuild_plugin.cmx
       was built with -for-pack Ocamlbuild_pack, but the 
       current unit Myocamlbuild is not
Command exited with code 2.
pkg.ml: [ERROR] cmd ['ocamlbuild' '-use-ocamlfind' '-classic-display' '-j' '4' '-tag' 'debug'
     '-build-dir' '_build' 'opam' 'pkg/META' 'CHANGES.md' 'LICENSE.md'
     'README.md' 'src/mtime.a' 'src/mtime.cmxa' 'src/mtime.cma'
     'src/mtime.cmx' 'src/mtime.cmi' 'src/mtime.mli' 'src/mtime_top.a'
     'src/mtime_top.cmxa' 'src/mtime_top.cma' 'src/mtime_top.cmx'
     'src/mtime_top_init.ml' 'doc/index.mld' 'src-os/mtime_clock.a'
     'src-os/mtime_clock.cmxa' 'src-os/mtime_clock.cma'
     'src-os/mtime_clock.cmx' 'src-os/mtime_clock.cmi'
     'src-os/mtime_clock.mli' 'src-os/dllmtime_clock_stubs.so'
     'src-os/libmtime_clock_stubs.a' 'test-os/min_os.ml']: exited with 10
```
What is a possible fix for the same?

**Comment by dbuenzli** [comment]
I don't know. Could you please try with the latest version `mtime.1.4.0` ? According to http://check.ocamllabs.io/ it compiles fine on 5.0.0.

Also it rather looks like a problem with `ocamlbuild` itself.

**Comment by shakthimaan** [comment]
I tried updating to the latest `ocamlbuild.0.14.1` and using `mtime.1.4.0`, and the same error occurs. A complete build log from CI is available at:
https://multicore.ci.ocamllabs.io:8100/job/2022-09-27/101624-ci-ocluster-build-0caea1

**Comment by dbuenzli** [comment]
There are no more details in the build log. I still suspect this is a problem with `ocamlbuild`. Maybe try with another package that has an `myocamlbuild.ml` file, like `ptime`, `tgls` or `tsdl` to see if you witness the same error. Also maybe @kit-ty-kate has a hint ?

**Comment by kit-ty-kate** [comment]
No idea. I don’t have much time to look at it in details right now but maybe @dra27 would know.

**Comment by dra27** [comment]
I agree that this looks like an ocamlbuild issue and is a side-effect of the recently merged https://github.com/ocaml/ocaml/pull/1391.

**Comment by kit-ty-kate** [comment]
If so, to me it looks like a bug in the compiler instead. It seems weird to me to have this error trigger when compiling an executable

**Comment by kit-ty-kate** [comment]
Ok nevermind it was a bug in ocamlbuild.
@shakthimaan this PR should fix your issue https://github.com/ocaml/ocamlbuild/pull/319

**Comment by dbuenzli** [comment]
Thanks all !
