### ISSUE TITLE
max_span = -1e-09s

### ISSUE THREAD

**Issue by talex5** [dbuenzli/mtime#46]
I'm trying to convert OCaml durations (floats) to Mtime.Span.t, but having some trouble. `Int64.of_float` says:

> If the truncated floating-point number is outside the range `[Int64.min_int, Int64.max_int]`, no exception is raised, and an unspecified, platform-dependent integer is returned.

So I want to check the number is in-range before converting. But `max_span` seems to behave strangely:

```ocaml
utop # #require "fmt,mtime";;

utop # Mtime.Span.to_s (Mtime.Span.max_span);;
- : float = -1e-09

utop # Fmt.to_to_string Mtime.Span.pp Mtime.Span.max_span;;
- : string = "-0.001us"
```

What's the recommended way to convert a float in seconds to a span? Mtime's `*` operator says:

> {b Warning.} Does not check for overflow or that [n] is positive. 

So I guess I can't use that.

**Comment by dbuenzli** [comment]
Not so strange, but certainly totally wrong :-) 

`max_span` is `-1L`, the module treats `int64` as unsigned integers. However it uses `Int64.to_float` in the floating [point conversions](https://github.com/dbuenzli/mtime/blob/master/src/mtime.ml#L72), this can't work unless your span is in `[0L;Int64.max_int]`.

**Comment by dbuenzli** [comment]
For now I would simply ignore these floating point conversions use `to_uint64_ns` and deal with that yourself. I don't think providing all these float constants and conversion functions was a great idea in the first place.

**Comment by dbuenzli** [comment]
But to go back to your original problem, you can check simply if your floating point number *in nanoseconds* is in the range `[0.0;Int64.to_float Int64.max_int]`, then use `Int64.of_float` and then use `Mtime.Span.of_uint64_ns`. 

(Technically you could have a wider range but you'll need a function that nows how to convert a float to an unsigned int64).

**Comment by talex5** [comment]
I'm using this for now:

```ocaml
  (* Converting floats via int64 is tricky when things overflow or go negative.
     Since we don't need to wait for more than 100 years, limit it to this: *)
  let too_many_ns = 0x8000000000000000.

  let span_of_s s =
    if s >= 0.0 then (
      let ns = s *. 1e9 in
      if ns >= too_many_ns then Mtime.Span.max_span
      else Mtime.Span.of_uint64_ns (Int64.of_float ns)
    ) else Mtime.Span.zero      (* Also happens for NaN and negative infinity *)
```
I wasn't convinced that negative ints would work correctly, especially if converted back again later, and since this is for a sleep operation it shouldn't matter much as long as it handles all reasonable periods.

**Comment by dbuenzli** [comment]
@talex5 I tried to clean up a bit all that mess on master. I removed all the deprecated float stuff in 1f9070b7dbf5906a2c8b. 

Then added `Mtime.Span.{to,of}_float_ns` in 0757ea47aba837ae with a slightly different behaviour than you propose: 

- On `Mtime.Span.to_float_ns` I adjust the result so as not to get the absurd result that is the title of this issue. But if your span is greater than 2^53 (~104 days), the result is imprecise.
- On `Mtime.Span.of_float_ns` I take only values in `[0.;2^53-1]` this ensures that your span is always honoured as you think. That limits us to 104 days spans, people who want more can play with `of_uint64_ns`.

Tell me what you think.

**Comment by talex5** [comment]
Seems reasonable. For my use, I'll continue using my version, because I want very long values to lead to a very long timeout (even if not exact).

**Comment by dbuenzli** [comment]
Ok thanks. 

> For my use, I'll continue using my version, because I want very long values to lead to a very long timeout (even if not exact).

Though that will lump `nan`, `infinity` and negative values in very long, you could do: 

```ocaml
let span_of_s s = 
  Option.value ~default:Mtime.Span.max_span (Mtime.Span.of_float_ns (s *. 1e9))
```
