### ISSUE TITLE
/usr/bin/ld: cannot find -lmtime_clock_stubs

### ISSUE THREAD

**Issue by talex5** [dbuenzli/mtime#48]
On various systems (including x86_32), mtime fails to link. It's easy to reproduce with dune by simply depending on `mtime.clock.os`, but it fails with `ocamlfind` too:

```
$ touch main.ml
$ ocamlfind ocamlc -output-complete-exe -linkpkg -package mtime.clock.os main.ml
/usr/bin/ld: cannot find -lmtime_clock_stubs
collect2: error: ld returned 1 exit status
File "main.ml", line 1:
Error: Error while building custom runtime system
```

I tried to run mtime's own tests, but:
```
$ ocaml pkg/pkg.ml test
pkg.ml: No tests to run.
```

Other packages with C stubs (e.g. `cstruct`) do work.

(@mseri reported this as an Eio bug at https://github.com/ocaml-multicore/eio/issues/407, but it doesn't seem like it has much to do with Eio)

**Comment by dbuenzli** [comment]
This must be https://github.com/dbuenzli/topkg/issues/140

A new release of `topkg` has been made two weeks ago but it hasn't been merged https://github.com/ocaml/opam-repository/pull/23019

**Comment by talex5** [comment]
OK, I'll close this then. Thanks!
